/** Educational chart pattern library (40+ formations). */

export type PatternCategory =
  | "reversal"
  | "continuation"
  | "candlestick"
  | "harmonic"
  | "gap";

export type ChartPattern = {
  id: string;
  nameLt: string;
  nameEn: string;
  category: PatternCategory;
  bias: "bullish" | "bearish" | "both";
  descriptionLt: string;
  descriptionEn: string;
  howToTradeLt: string;
  howToTradeEn: string;
};

export const CHART_PATTERNS: ChartPattern[] = [
  {
    id: "head-shoulders",
    nameLt: "Galva ir pečiai",
    nameEn: "Head & Shoulders",
    category: "reversal",
    bias: "bearish",
    descriptionLt: "Trys viršūnės: kairieji pečiai, aukštesnė galva, dešinieji pečiai.",
    descriptionEn: "Three peaks: left shoulder, higher head, right shoulder.",
    howToTradeLt: "Įėjimas po kaklo linijos pramušimo žemyn; SL virš dešiniojo pečio.",
    howToTradeEn: "Enter after neckline break down; SL above right shoulder.",
  },
  {
    id: "inv-head-shoulders",
    nameLt: "Apversta galva ir pečiai",
    nameEn: "Inverse Head & Shoulders",
    category: "reversal",
    bias: "bullish",
    descriptionLt: "Trys dugnai: pečiai ir gilesnė galva — dažnas dugno apsisukimas.",
    descriptionEn: "Three troughs with a deeper head — common bottom reversal.",
    howToTradeLt: "Įėjimas po kaklo linijos aukštyn; SL po dešiniuoju pečiu.",
    howToTradeEn: "Enter on neckline break up; SL below right shoulder.",
  },
  {
    id: "double-top",
    nameLt: "Dviguba viršūnė",
    nameEn: "Double Top",
    category: "reversal",
    bias: "bearish",
    descriptionLt: "Dvi panašios aukštumos su atrama tarp jų.",
    descriptionEn: "Two similar highs with support between them.",
    howToTradeLt: "Trumpinti po atramos pramušimo; SL virš antros viršūnės.",
    howToTradeEn: "Short after support break; SL above second high.",
  },
  {
    id: "double-bottom",
    nameLt: "Dvigubas dugnas",
    nameEn: "Double Bottom",
    category: "reversal",
    bias: "bullish",
    descriptionLt: "Du panašūs dugnai — potencialus apsisukimas aukštyn.",
    descriptionEn: "Two similar lows — potential upside reversal.",
    howToTradeLt: "Pirkti po pasipriešinimo pramušimo; SL po antru dugnu.",
    howToTradeEn: "Buy after resistance break; SL below second low.",
  },
  {
    id: "triple-top",
    nameLt: "Triguba viršūnė",
    nameEn: "Triple Top",
    category: "reversal",
    bias: "bearish",
    descriptionLt: "Trys atmetimai nuo to paties pasipriešinimo.",
    descriptionEn: "Three rejections from the same resistance.",
    howToTradeLt: "Įėjimas po horizontalios atramos pramušimo.",
    howToTradeEn: "Enter after horizontal support break.",
  },
  {
    id: "triple-bottom",
    nameLt: "Trigubas dugnas",
    nameEn: "Triple Bottom",
    category: "reversal",
    bias: "bullish",
    descriptionLt: "Trys atramos bandymai toje pačioje zonoje.",
    descriptionEn: "Three support tests in the same zone.",
    howToTradeLt: "Įėjimas po pasipriešinimo pramušimo aukštyn.",
    howToTradeEn: "Enter after resistance break upward.",
  },
  {
    id: "rising-wedge",
    nameLt: "Kylantis pleištas",
    nameEn: "Rising Wedge",
    category: "reversal",
    bias: "bearish",
    descriptionLt: "Kylančios atramos ir pasipriešinimo linijos, siaurėjančios.",
    descriptionEn: "Rising support and resistance converging.",
    howToTradeLt: "Dažnai bearish breakout žemyn; SL virš pleišto.",
    howToTradeEn: "Often bearish break down; SL above wedge.",
  },
  {
    id: "falling-wedge",
    nameLt: "Krintantis pleištas",
    nameEn: "Falling Wedge",
    category: "reversal",
    bias: "bullish",
    descriptionLt: "Krintančios linijos, siaurėjantis diapazonas.",
    descriptionEn: "Falling lines with a narrowing range.",
    howToTradeLt: "Bullish breakout aukštyn; SL po apatine linija.",
    howToTradeEn: "Bullish break up; SL below lower line.",
  },
  {
    id: "bull-flag",
    nameLt: "Bull vėliava",
    nameEn: "Bull Flag",
    category: "continuation",
    bias: "bullish",
    descriptionLt: "Stiprus kilimas (stiebas) + trumpa konsolidacija žemyn.",
    descriptionEn: "Strong rally (pole) plus short downward consolidation.",
    howToTradeLt: "Įėjimas po vėliavos pramušimo aukštyn; tikslas ≈ stiebo ilgis.",
    howToTradeEn: "Enter on flag break up; target ≈ pole height.",
  },
  {
    id: "bear-flag",
    nameLt: "Bear vėliava",
    nameEn: "Bear Flag",
    category: "continuation",
    bias: "bearish",
    descriptionLt: "Stiprus kritimas + trumpa konsolidacija aukštyn.",
    descriptionEn: "Sharp drop plus brief upward consolidation.",
    howToTradeLt: "Trumpinti po pramušimo žemyn; tikslas ≈ stiebas.",
    howToTradeEn: "Short on break down; target ≈ pole.",
  },
  {
    id: "bull-pennant",
    nameLt: "Bull vėliavėlė",
    nameEn: "Bull Pennant",
    category: "continuation",
    bias: "bullish",
    descriptionLt: "Simetriškas trikampis po stipraus kilimo.",
    descriptionEn: "Symmetrical triangle after a strong rally.",
    howToTradeLt: "Breakout aukštyn su volume; SL po vėliavėle.",
    howToTradeEn: "Break up with volume; SL below pennant.",
  },
  {
    id: "bear-pennant",
    nameLt: "Bear vėliavėlė",
    nameEn: "Bear Pennant",
    category: "continuation",
    bias: "bearish",
    descriptionLt: "Simetriškas trikampis po kritimo.",
    descriptionEn: "Symmetrical triangle after a decline.",
    howToTradeLt: "Breakout žemyn; SL virš formacijos.",
    howToTradeEn: "Break down; SL above formation.",
  },
  {
    id: "asc-triangle",
    nameLt: "Kylantis trikampis",
    nameEn: "Ascending Triangle",
    category: "continuation",
    bias: "bullish",
    descriptionLt: "Plokščias pasipriešinimas + kylanti atrama.",
    descriptionEn: "Flat resistance with rising support.",
    howToTradeLt: "Pirkti pramušus horizontalią liniją.",
    howToTradeEn: "Buy on horizontal break.",
  },
  {
    id: "desc-triangle",
    nameLt: "Krintantis trikampis",
    nameEn: "Descending Triangle",
    category: "continuation",
    bias: "bearish",
    descriptionLt: "Plokščia atrama + krintantis pasipriešinimas.",
    descriptionEn: "Flat support with descending resistance.",
    howToTradeLt: "Trumpinti po atramos pramušimo.",
    howToTradeEn: "Short on support break.",
  },
  {
    id: "sym-triangle",
    nameLt: "Simetriškas trikampis",
    nameEn: "Symmetrical Triangle",
    category: "continuation",
    bias: "both",
    descriptionLt: "Abi linijos susilieja — kryptis pagal breakout.",
    descriptionEn: "Both lines converge — direction follows breakout.",
    howToTradeLt: "Prekiauti breakout kryptimi; vengti vidurio.",
    howToTradeEn: "Trade breakout direction; avoid mid-range.",
  },
  {
    id: "rectangle",
    nameLt: "Stačiakampis",
    nameEn: "Rectangle",
    category: "continuation",
    bias: "both",
    descriptionLt: "Horizontalus diapazonas tarp atramos ir pasipriešinimo.",
    descriptionEn: "Horizontal range between support and resistance.",
    howToTradeLt: "Breakout arba range prekyba nuo kraštų.",
    howToTradeEn: "Breakout or range-trade the edges.",
  },
  {
    id: "cup-handle",
    nameLt: "Taurė su rankena",
    nameEn: "Cup and Handle",
    category: "continuation",
    bias: "bullish",
    descriptionLt: "U formos dugnas + trumpa rankenos korekcija.",
    descriptionEn: "U-shaped base plus a short handle pullback.",
    howToTradeLt: "Įėjimas po rankenos pramušimo; SL po rankena.",
    howToTradeEn: "Enter on handle break; SL below handle.",
  },
  {
    id: "rounding-bottom",
    nameLt: "Apvalus dugnas",
    nameEn: "Rounding Bottom",
    category: "reversal",
    bias: "bullish",
    descriptionLt: "Lėtas U formos apsisukimas iš meškų į bulius.",
    descriptionEn: "Slow U-shaped shift from bearish to bullish.",
    howToTradeLt: "Pirkti patvirtinus pasipriešinimo pramušimą.",
    howToTradeEn: "Buy after confirmed resistance break.",
  },
  {
    id: "rounding-top",
    nameLt: "Apvali viršūnė",
    nameEn: "Rounding Top",
    category: "reversal",
    bias: "bearish",
    descriptionLt: "Lėtas apsisukimas žemyn po piko.",
    descriptionEn: "Slow rollover after a peak.",
    howToTradeLt: "Trumpinti po atramos pramušimo.",
    howToTradeEn: "Short after support break.",
  },
  {
    id: "channel-up",
    nameLt: "Kylantis kanalas",
    nameEn: "Ascending Channel",
    category: "continuation",
    bias: "bullish",
    descriptionLt: "Lygiagrečios kylančios atramos ir pasipriešinimo linijos.",
    descriptionEn: "Parallel rising support and resistance.",
    howToTradeLt: "Pirkti nuo apatinės linijos; SL po kanalu.",
    howToTradeEn: "Buy lower line; SL below channel.",
  },
  {
    id: "channel-down",
    nameLt: "Krintantis kanalas",
    nameEn: "Descending Channel",
    category: "continuation",
    bias: "bearish",
    descriptionLt: "Lygiagrečios krintančios linijos.",
    descriptionEn: "Parallel descending lines.",
    howToTradeLt: "Trumpinti nuo viršutinės linijos.",
    howToTradeEn: "Short from upper line.",
  },
  {
    id: "broadening",
    nameLt: "Plečiantis darinys",
    nameEn: "Broadening Formation",
    category: "reversal",
    bias: "both",
    descriptionLt: "Didėjantis volatilumas, plačios sūpynės.",
    descriptionEn: "Expanding volatility with wide swings.",
    howToTradeLt: "Atsargiai — dažnai chaosas prieš apsisukimą.",
    howToTradeEn: "Caution — often chaos before reversal.",
  },
  {
    id: "diamond",
    nameLt: "Deimantas",
    nameEn: "Diamond Top/Bottom",
    category: "reversal",
    bias: "both",
    descriptionLt: "Plečiantis + siaurėjantis darinys kaip deimantas.",
    descriptionEn: "Expand-then-contract diamond shape.",
    howToTradeLt: "Prekiauti breakout; mažesni dydžiai dėl sudėtingumo.",
    howToTradeEn: "Trade the breakout; smaller size due to complexity.",
  },
  {
    id: "engulfing-bull",
    nameLt: "Bullish engulfing",
    nameEn: "Bullish Engulfing",
    category: "candlestick",
    bias: "bullish",
    descriptionLt: "Žalia žvakė visiškai apgaubia ankstesnę raudoną.",
    descriptionEn: "Green candle fully engulfs prior red candle.",
    howToTradeLt: "Patvirtinti atramoje; SL po engulfing žvakės.",
    howToTradeEn: "Confirm at support; SL below engulfing candle.",
  },
  {
    id: "engulfing-bear",
    nameLt: "Bearish engulfing",
    nameEn: "Bearish Engulfing",
    category: "candlestick",
    bias: "bearish",
    descriptionLt: "Raudona žvakė apgaubia ankstesnę žalią.",
    descriptionEn: "Red candle engulfs prior green.",
    howToTradeLt: "Patvirtinti pasipriešinime; SL virš žvakės.",
    howToTradeEn: "Confirm at resistance; SL above candle.",
  },
  {
    id: "hammer",
    nameLt: "Plaktukas",
    nameEn: "Hammer",
    category: "candlestick",
    bias: "bullish",
    descriptionLt: "Ilgas apatinis šešėlis dugne — potencialus atšokimas.",
    descriptionEn: "Long lower wick at a low — potential bounce.",
    howToTradeLt: "Laukti patvirtinimo kitos žvakės; SL po šešėliu.",
    howToTradeEn: "Wait for next-candle confirm; SL below wick.",
  },
  {
    id: "shooting-star",
    nameLt: "Krintanti žvaigždė",
    nameEn: "Shooting Star",
    category: "candlestick",
    bias: "bearish",
    descriptionLt: "Ilgas viršutinis šešėlis viršūnėje.",
    descriptionEn: "Long upper wick at a high.",
    howToTradeLt: "Trumpinti po patvirtinimo; SL virš šešėlio.",
    howToTradeEn: "Short after confirm; SL above wick.",
  },
  {
    id: "doji",
    nameLt: "Doji",
    nameEn: "Doji",
    category: "candlestick",
    bias: "both",
    descriptionLt: "Atidarymas ≈ uždarymas — neryžtingumas.",
    descriptionEn: "Open ≈ close — indecision.",
    howToTradeLt: "Naudoti kaip kontekstą, ne vienintelį signalą.",
    howToTradeEn: "Use as context, not a standalone signal.",
  },
  {
    id: "morning-star",
    nameLt: "Ryto žvaigždė",
    nameEn: "Morning Star",
    category: "candlestick",
    bias: "bullish",
    descriptionLt: "Trys žvakės: kritimas, maža žvakė, stiprus kilimas.",
    descriptionEn: "Three candles: drop, small body, strong rally.",
    howToTradeLt: "Įėjimas po trečios žvakės; SL po žvaigžde.",
    howToTradeEn: "Enter after third candle; SL below star.",
  },
  {
    id: "evening-star",
    nameLt: "Vakaro žvaigždė",
    nameEn: "Evening Star",
    category: "candlestick",
    bias: "bearish",
    descriptionLt: "Trys žvakės: kilimas, maža žvakė, kritimas.",
    descriptionEn: "Three candles: rally, small body, drop.",
    howToTradeLt: "Trumpinti po trečios; SL virš žvaigždės.",
    howToTradeEn: "Short after third; SL above star.",
  },
  {
    id: "harami-bull",
    nameLt: "Bullish harami",
    nameEn: "Bullish Harami",
    category: "candlestick",
    bias: "bullish",
    descriptionLt: "Maža žalia žvakė didelės raudonos viduje.",
    descriptionEn: "Small green inside a large red body.",
    howToTradeLt: "Laukti patvirtinimo aukštyn.",
    howToTradeEn: "Wait for upside confirmation.",
  },
  {
    id: "harami-bear",
    nameLt: "Bearish harami",
    nameEn: "Bearish Harami",
    category: "candlestick",
    bias: "bearish",
    descriptionLt: "Maža raudona didelės žalios viduje.",
    descriptionEn: "Small red inside a large green body.",
    howToTradeLt: "Laukti patvirtinimo žemyn.",
    howToTradeEn: "Wait for downside confirmation.",
  },
  {
    id: "three-white",
    nameLt: "Trys balti kariai",
    nameEn: "Three White Soldiers",
    category: "candlestick",
    bias: "bullish",
    descriptionLt: "Trys iš eilės stiprios žalios žvakės.",
    descriptionEn: "Three consecutive strong green candles.",
    howToTradeLt: "Trend continuation; SL po pirmos žvakės dugnu.",
    howToTradeEn: "Trend continuation; SL below first low.",
  },
  {
    id: "three-black",
    nameLt: "Trys juodi varnai",
    nameEn: "Three Black Crows",
    category: "candlestick",
    bias: "bearish",
    descriptionLt: "Trys iš eilės stiprios raudonos žvakės.",
    descriptionEn: "Three consecutive strong red candles.",
    howToTradeLt: "Trend continuation žemyn; SL virš pirmos.",
    howToTradeEn: "Downtrend continuation; SL above first high.",
  },
  {
    id: "piercing",
    nameLt: "Pradūrimo linija",
    nameEn: "Piercing Line",
    category: "candlestick",
    bias: "bullish",
    descriptionLt: "Žalia žvakė užsidaro giliai į ankstesnę raudoną.",
    descriptionEn: "Green closes deep into prior red body.",
    howToTradeLt: "Atramoje; SL po antra žvakė.",
    howToTradeEn: "At support; SL below second candle.",
  },
  {
    id: "dark-cloud",
    nameLt: "Tamsi debesų skraistė",
    nameEn: "Dark Cloud Cover",
    category: "candlestick",
    bias: "bearish",
    descriptionLt: "Raudona užsidaro giliai į ankstesnę žalią.",
    descriptionEn: "Red closes deep into prior green.",
    howToTradeLt: "Pasipriešinime; SL virš debesies.",
    howToTradeEn: "At resistance; SL above the cloud.",
  },
  {
    id: "gartley",
    nameLt: "Gartley",
    nameEn: "Gartley",
    category: "harmonic",
    bias: "both",
    descriptionLt: "Harmoninis XA-AB-BC-CD darinys su Fibonacci lygiais.",
    descriptionEn: "Harmonic XA-AB-BC-CD with Fibonacci ratios.",
    howToTradeLt: "Įėjimas D taške; griežtas SL už X.",
    howToTradeEn: "Enter at D; tight SL beyond X.",
  },
  {
    id: "bat",
    nameLt: "Šikšnosparnis (Bat)",
    nameEn: "Bat",
    category: "harmonic",
    bias: "both",
    descriptionLt: "Harmonika su gilesniu B retracement nei Gartley.",
    descriptionEn: "Harmonic with deeper B retracement than Gartley.",
    howToTradeLt: "PRZ zona D; mažas dydis, aiškus invalidavimas.",
    howToTradeEn: "PRZ at D; small size, clear invalidation.",
  },
  {
    id: "butterfly",
    nameLt: "Drugelis",
    nameEn: "Butterfly",
    category: "harmonic",
    bias: "both",
    descriptionLt: "Išplėstas CD — dažnai ekstremali zona.",
    descriptionEn: "Extended CD — often an extreme zone.",
    howToTradeLt: "Kontrarian įėjimas D; greitas TP į 38–61%.",
    howToTradeEn: "Contrarian at D; quick TP to 38–61%.",
  },
  {
    id: "crab",
    nameLt: "Krabų darinys",
    nameEn: "Crab",
    category: "harmonic",
    bias: "both",
    descriptionLt: "Labai išplėstas CD (≈1.618 XA).",
    descriptionEn: "Very extended CD (≈1.618 XA).",
    howToTradeLt: "Tik su papildomu patvirtinimu; siauras SL.",
    howToTradeEn: "Only with extra confirmation; tight SL.",
  },
  {
    id: "abcd",
    nameLt: "ABCD",
    nameEn: "ABCD",
    category: "harmonic",
    bias: "both",
    descriptionLt: "Paprasta keturių taškų impulsų simetrija.",
    descriptionEn: "Simple four-point impulse symmetry.",
    howToTradeLt: "Įėjimas D ≈ AB projekcija; SL už C/D ekstremumo.",
    howToTradeEn: "Enter D ≈ AB projection; SL beyond C/D extreme.",
  },
  {
    id: "gap-up",
    nameLt: "Gap aukštyn",
    nameEn: "Gap Up",
    category: "gap",
    bias: "bullish",
    descriptionLt: "Atidarymas gerokai virš ankstesnio uždarymo.",
    descriptionEn: "Open well above prior close.",
    howToTradeLt: "Continuation arba fill-the-gap strategijos.",
    howToTradeEn: "Continuation or fill-the-gap strategies.",
  },
  {
    id: "gap-down",
    nameLt: "Gap žemyn",
    nameEn: "Gap Down",
    category: "gap",
    bias: "bearish",
    descriptionLt: "Atidarymas gerokai žemiau ankstesnio uždarymo.",
    descriptionEn: "Open well below prior close.",
    howToTradeLt: "Meškų continuation arba gap fill.",
    howToTradeEn: "Bearish continuation or gap fill.",
  },
  {
    id: "island-rev",
    nameLt: "Salos apsisukimas",
    nameEn: "Island Reversal",
    category: "gap",
    bias: "both",
    descriptionLt: "Gap į salą, tada gap atgal — staigus apsisukimas.",
    descriptionEn: "Gap into an island, then gap back — sharp reversal.",
    howToTradeLt: "Įėjimas po antro gap; SL salos viduje.",
    howToTradeEn: "Enter after second gap; SL inside island.",
  },
];

export const ACADEMY_TERMS: {
  id: string;
  termLt: string;
  termEn: string;
  defLt: string;
  defEn: string;
}[] = [
  {
    id: "rr",
    termLt: "R:R (Risk-Reward)",
    termEn: "R:R (Risk-Reward)",
    defLt: "Potencialaus pelno ir rizikos santykis (pvz. 1:2).",
    defEn: "Ratio of potential reward to risk (e.g. 1:2).",
  },
  {
    id: "sl",
    termLt: "Stop Loss / Invalidavimas",
    termEn: "Stop Loss / Invalidation",
    defLt: "Kaina, kurioje setup'as laikomas neteisingu.",
    defEn: "Price where the setup is considered invalid.",
  },
  {
    id: "tp",
    termLt: "Take Profit",
    termEn: "Take Profit",
    defLt: "Išėjimo zonos pelnui fiksuoti.",
    defEn: "Exit zones to lock in profit.",
  },
  {
    id: "ema",
    termLt: "EMA",
    termEn: "EMA",
    defLt: "Eksponentinis slenkantis vidurkis — greitesnis už SMA.",
    defEn: "Exponential moving average — faster than SMA.",
  },
  {
    id: "rsi",
    termLt: "RSI",
    termEn: "RSI",
    defLt: "Santykinio stiprumo indeksas (momentum).",
    defEn: "Relative Strength Index (momentum).",
  },
  {
    id: "obv",
    termLt: "OBV / kapitalo srautas",
    termEn: "OBV / capital flow",
    defLt: "Tūrio krypties kaupimas — inflow/outflow proxy.",
    defEn: "Cumulative volume direction — inflow/outflow proxy.",
  },
  {
    id: "sr",
    termLt: "Atrama / Pasipriešinimas",
    termEn: "Support / Resistance",
    defLt: "Zonos, kur kaina istoriškai stabdė arba atšoko.",
    defEn: "Zones where price historically paused or bounced.",
  },
  {
    id: "bias",
    termLt: "Bias (kryptis)",
    termEn: "Bias",
    defLt: "Bendras setup'o polinkis: bullish / bearish / neutral.",
    defEn: "Overall setup lean: bullish / bearish / neutral.",
  },
  {
    id: "confluence",
    termLt: "Konfluencija",
    termEn: "Confluence",
    defLt: "Keli indikatoriai / lygiai sutampa.",
    defEn: "Multiple indicators / levels aligning.",
  },
  {
    id: "liquidity",
    termLt: "Likvidumas",
    termEn: "Liquidity",
    defLt: "Kiek lengvai galima įeiti/išeiti be slydimo.",
    defEn: "How easily you can enter/exit without slip.",
  },
  {
    id: "timeframe",
    termLt: "Laiko rėmas",
    termEn: "Timeframe",
    defLt: "Žvakės trukmė (15m, 1h, 4h…).",
    defEn: "Candle duration (15m, 1h, 4h…).",
  },
  {
    id: "position",
    termLt: "Pozicijos dydis",
    termEn: "Position size",
    defLt: "Kiek rizikuoti pagal SL atstumą ir % kapitalo.",
    defEn: "How much to risk given SL distance and % of capital.",
  },
  {
    id: "breakout",
    termLt: "Breakout",
    termEn: "Breakout",
    defLt: "Kainos pramušimas pro S/R ar formaciją.",
    defEn: "Price breaking through S/R or a pattern.",
  },
  {
    id: "retest",
    termLt: "Retest",
    termEn: "Retest",
    defLt: "Grįžimas patikrinti pramuštą lygį.",
    defEn: "Return to test a broken level.",
  },
  {
    id: "orderflow",
    termLt: "Order flow (proxy)",
    termEn: "Order flow (proxy)",
    defLt: "Tūrio + uždarymo vietos diapazone įvertinimas.",
    defEn: "Volume plus close location in the range.",
  },
  {
    id: "setup-score",
    termLt: "Setup Score",
    termEn: "Setup Score",
    defLt: "A+…F balas pagal patvirtinimų skaičių.",
    defEn: "A+…F grade from confirmation count.",
  },
  {
    id: "pip",
    termLt: "Pip / tick",
    termEn: "Pip / tick",
    defLt: "Minimalus kainos judesio vienetas (priklauso nuo instrumento).",
    defEn: "Minimal price increment (instrument-dependent).",
  },
  {
    id: "drawdown",
    termLt: "Drawdown",
    termEn: "Drawdown",
    defLt: "Nuosmukis nuo piko iki dugno sąskaitoje.",
    defEn: "Peak-to-trough decline in the account.",
  },
];
